name: Deploy to prod

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Frontend
              run: |
                  npm ci
                  npm run build

            - name: Deploy
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.MAIN_SERVER_IP }}
                  username: ${{ secrets.DEPLOY_USER }}
                  password: ${{ secrets.MAIN_DEPLOY_PASSWORD }}
                  source: "./build"
                  target: /home/deploy/Observer

            - name: Start Nginx
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.MAIN_SERVER_IP }}
                  username: ${{ secrets.DEPLOY_USER }}
                  password: ${{ secrets.MAIN_DEPLOY_PASSWORD }}
                  script: |
                      if sudo systemctl is-active nginx; then
                        echo "Nginx is already running, no action needed."
                      else
                        sudo systemctl restart nginx
                        echo "Restarted Nginx."
                      fi
