name: Deploy to prod

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Frontend
              run: |
                  npm ci
                  npm run build

            - name: Deploy
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.PROD_IP }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  source: "./build"
                  target: /home/deploy/observer

            - name: Start Nginx
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.PROD_IP }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  script: |
                      sudo systemctl restart nginx
                      echo "Nginx restarted."
